# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
  - REPOSITORY_TRIVY
  - REPOSITORY_CHECKOV
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_DEVSKIM
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
FILTER_REGEX_EXCLUDE: "(.github|.devcontainer|ld52/assets/vendor)"
